.PHONY: install run dataset dataset-upload

install:
	cd live && $(MAKE) install

run:
	cd live && $(MAKE) run

dataset:
	cd live && $(MAKE) dataset

dataset-upload:
	cd live && $(MAKE) dataset-upload

